[package]
name = "todo_backend"
version = "0.1.0"
edition = "2024"

[dependencies]

axum = "0.8.8"
sqlx = { version = "0.8", features = ["runtime-tokio", "postgres"] }
tokio = { version = "1.48.0", features = ["macros", "rt-multi-thread"] }
serde = { version = "1", features = ["derive"] }
