apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - manifests/deployment.yml
  - manifests/service.yml
  - manifests/backend/deployment.yml
  - manifests/backend/service.yml
  - manifests/reminder/cronJob.yml
  - manifests/postgres/service.yml
  - manifests/postgres/statefulSet.yml

images:
  - name: IMAGES/APP
    newName: tomjtoth/devops-with-kubernetes:todo-app-2.6
  - name: IMAGES/BACKEND
    newName: tomjtoth/devops-with-kubernetes:todo-backend-2.10
  - name: IMAGES/REMINDER
    newName: tomjtoth/devops-with-kubernetes:todo-reminder-2.9
