apiVersion: v1
kind: Service
metadata:
  namespace: exercises
  name: pingpong-svc
spec:
  type: ClusterIP
  selector:
    app: pingpong
  ports:
    - port: 55555
      protocol: TCP
      targetPort: 3000
