apiVersion: batch/v1
kind: CronJob
metadata:
  namespace: project
  name: reminder
spec:
  schedule: "0 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: reminder
              image: IMAGES/REMINDER
              imagePullPolicy: Always
              env:
                - name: DATABASE_URL
                  value: postgres://postgres:password@postgres-svc

              resources:
                limits:
                  cpu: 500m
                  memory: 20Mi

                requests:
                  cpu: 100m
                  memory: 5Mi

          restartPolicy: OnFailure
