apiVersion: v1
kind: ConfigMap
metadata:
  namespace: project
  name: postgres-conf
data:
  init.sql: |
    CREATE TABLE IF NOT EXISTS todos (
      id SERIAL,
      todo TEXT
    );

    INSERT INTO todos (todo) VALUES 
      ('Learn Rust'),
      ('Learn Dioxus'),
      ('Build something');
