name: CD

on:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy:
    if: contains(github.event.head_commit.message, '#deploy ')
    name: Generate Docker image
    runs-on: ubuntu-latest

    steps:
      - name: Get tag
        env:
          COMMIT_MSG: ${{ github.event.head_commit.message }}
        run: |
          # https://regex101.com/r/H4BBVD/1
          read -r APP VER <<<"$(
            printf '%s' "$COMMIT_MSG" \
            | sed -nE 's/.*#deploy\s+([[:alnum:]-]+)\s*:\s*([0-9]+\.[0-9]+).*/\1 \2/p'
          )"
          [ -z "$APP" ] && exit 1
          echo "TAG=$APP-$VER" >> $GITHUB_ENV

          FOLDER=$(
            printf '%s' "$APP" \
            | sed -nE 's/[^[:alnum:]_]+/_/gp'
          )
          echo "FOLDER=$FOLDER" >> $GITHUB_ENV

      - name: Checkout
        uses: actions/checkout@v6

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build image
        uses: docker/build-push-action@v6
        with:
          context: ./${{ env.FOLDER }}
          push: true
          tags: tomjtoth/devops-with-kubernetes:${{ env.TAG }}
          cache-from: type=gha,scope=shared
          cache-to: type=gha,mode=max,scope=shared
