name: CD

on:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy:
    if: contains(github.event.head_commit.message, '#deploy ')
    name: Generate Docker image
    runs-on: ubuntu-latest

    steps:
      - name: Get tag
        env:
          COMMIT_MSG: ${{ github.event.head_commit.message }}
        run: |
          # https://regex101.com/r/H4BBVD
          regex='#deploy +(PROD +)?([[:alnum:]-]+) *(\(([[:alnum:]]+)\))?: *([0-9]+\.[0-9]+)'

          if [[ "$COMMIT_MSG" =~ $regex ]]; then
            PROD=${BASH_REMATCH[1]}
            APP=${BASH_REMATCH[2]}
            PH=${BASH_REMATCH[4]}
            VER=${BASH_REMATCH[5]}
          else
            exit 1
          fi

          echo "IMAGE=tomjtoth/devops-with-kubernetes:$APP-$VER" >> $GITHUB_ENV
          echo "PLACEHOLDER=${PH:-${APP^^}}" >> $GITHUB_ENV
          echo "KUSTOMIZE_PROD_CHK=$PROD" >> $GITHUB_ENV

          FOLDER=$(
            printf '%s' "$APP" \
            | sed -E 's/[^[:alnum:]_]+/_/g'
          )
          echo "FOLDER=$FOLDER" >> $GITHUB_ENV

      - name: Checkout
        uses: actions/checkout@v6

      - name: decide if can run Kustomize
        run: |
          if [ -f "$FOLDER/manifests/base/kustomization.yml" ]; then
            echo "KUSTOMIZE=1" >> $GITHUB_ENV
          fi

          if [ -n "$KUSTOMIZE_PROD_CHK" ] && \
             [ -f "$FOLDER/manifests/overlays/prod/kustomization.yml" ]
          then
            echo "KUSTOMIZE_PROD=1" >> $GITHUB_ENV
          fi

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build image
        uses: docker/build-push-action@v6
        with:
          context: ./${{ env.FOLDER }}
          push: true
          tags: ${{ env.IMAGE }}
          cache-from: type=gha,scope=shared
          cache-to: type=gha,mode=max,scope=shared

      - name: Set up Kustomize
        if: env.KUSTOMIZE == '1'
        uses: imranismail/setup-kustomize@v2

      - name: Update base image
        if: env.KUSTOMIZE == '1'
        working-directory: ./${{ env.FOLDER }}/manifests/base
        run: kustomize edit set image IMAGES/${{ env.PLACEHOLDER }}=${{ env.IMAGE }}

      - name: commit base kustomization.yaml to GitHub
        if: env.KUSTOMIZE == '1'
        uses: EndBug/add-and-commit@v9
        with:
          add: "${{ env.FOLDER }}/manifests/base/kustomization.yml"
          message: New version released ${{ env.IMAGE }}

      - name: Update prod image also
        if: env.KUSTOMIZE_PROD == '1'
        working-directory: ./${{ env.FOLDER }}/manifests/overlays/prod
        run: kustomize edit set image IMAGES/${{ env.PLACEHOLDER }}=${{ env.IMAGE }}

      - name: commit prod kustomization.yaml to GitHub also
        if: env.KUSTOMIZE_PROD == '1'
        uses: EndBug/add-and-commit@v9
        with:
          add: "${{ env.FOLDER }}/manifests/overlays/prod/kustomization.yml"
          message: New version released ${{ env.IMAGE }} to prod
